In [0]:
import numpy as np

In [0]:
# Minimax
class MiniMax:
    
    def end(self, state):
        return self.evaluation(state)[1]!=0 or np.all(state != 0)
    
    def action(self, state, pos, turn):
        if(pos<1 or pos>9):
            return []
        x = int((pos-1)/3)
        y = (pos-1)%3
        if(state[x][y] == 0):
            tableCopy = np.copy(state)
            tableCopy[x][y] = turn
            return tableCopy
        else:
            return []
        
    def getStates(self, state, turn):
        nextStates = []
        for i in range(1,10):
            tableCopy = self.action(state, i, turn)
            if(len(tableCopy) != 0):
                nextStates.append(tableCopy)
        return nextStates

    def evaluation(self, state):
        sum_fil = np.sum(state, axis=1)
        sum_col = np.sum(state, axis=0)
        sum_dia1 = np.trace(state)
        sum_dia2 = np.trace(np.flip(state, axis = 1))
        r = (2*np.random.rand()-1)/10
        
        if(np.any(sum_fil == 3) or np.any(sum_col == 3) or sum_dia1 == 3 or sum_dia2 == 3):
            return 1 + r, 1
        if(np.any(sum_fil == -3) or np.any(sum_col == -3) or sum_dia1 == -3 or sum_dia2 == -3):
            return -1 + r, -1
        return 0 + r, 0
    
    def minimax(self, state, turn, level):
        nextNearStates =  self.getStates(state, turn)
        nextStates = np.copy(nextNearStates)
        if(level > 1 and not np.any([self.end(i) for i in nextStates])):
            nextStates = [self.minimax(i, -turn, level-1)[0] for i in nextStates]
        evaluations = [self.evaluation(i)[0] for i in nextStates]
        indexBetter = np.argmax(evaluations) if(turn==1) else np.argmin(evaluations)
        return nextStates[indexBetter], nextNearStates[indexBetter]

In [3]:
def getInput(table, minimax, turn):
    try:
        aux = minimax.action(table, int(input()), turn)
        if(len(aux)==0):
            raise Exception()
        return aux
    except:
        print("Invalid!")
        return getInput(table, minimax, turn)

init = 's'
while(init=='s'):
    minimax = MiniMax()
    table = np.array([
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
    ])
    try:
        level = int(input("Level(1-9): "))
        turn = int(input("Turn(1/-1): "))
    except:
        level = 9
        turn = 1
        print("Level:",level)
        print("Turn:",turn)
    print('-----------------')
    
    for i in range(100):
        print(table)
        print('-----------------')
        if(minimax.end(table)):
            winner = minimax.evaluation(table)[1]
            if(winner==1):
                print("Winner 1!")
            elif(winner==-1):
                print("Winner -1!")
            else:
                print("Draw!")
            break

        if(turn == 1):
            print("Thinking...")
            table = minimax.minimax(table, turn, level)[1]
        else:
            table = getInput(table, minimax, turn)
        turn = -turn
    init = input("Start?(s/n): ")

Level(1-9): 5
Turn(1/-1): 1
-----------------
[[0 0 0]
 [0 0 0]
 [0 0 0]]
-----------------
Thinking...
[[0 0 0]
 [0 1 0]
 [0 0 0]]
-----------------
1
[[-1  0  0]
 [ 0  1  0]
 [ 0  0  0]]
-----------------
Thinking...
[[-1  0  0]
 [ 0  1  1]
 [ 0  0  0]]
-----------------
4
[[-1  0  0]
 [-1  1  1]
 [ 0  0  0]]
-----------------
Thinking...
[[-1  0  0]
 [-1  1  1]
 [ 1  0  0]]
-----------------
3
[[-1  0 -1]
 [-1  1  1]
 [ 1  0  0]]
-----------------
Thinking...
[[-1  1 -1]
 [-1  1  1]
 [ 1  0  0]]
-----------------
9
[[-1  1 -1]
 [-1  1  1]
 [ 1  0 -1]]
-----------------
Thinking...
[[-1  1 -1]
 [-1  1  1]
 [ 1  1 -1]]
-----------------
Winner 1!
Start?(s/n): n
